name: CI

on:
  push:
    branches: [main]
    paths:
      - '**/pyproject.toml'
      - '**/requirements.txt'
      - '**/setup.py'
      - '**/*.py'
      - '.github/workflows/ci-python-template.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/pyproject.toml'
      - '**/requirements.txt'
      - '**/setup.py'
      - '**/*.py'
      - '.github/workflows/ci-python-template.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Install dependencies
        run: uv sync --dev
      
      - name: Run linting
        run: uv run ruff check src/ || true
      
      - name: Run tests
        run: uv run pytest tests/ -v --tb=short || true

  convert-to-draft:
    name: Convert to Draft on Failure
    runs-on: ubuntu-latest
    needs: [test]
    if: failure() && github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: Convert PR to Draft
        uses: actions/github-script@v7
        with:
          script: |
            const mutation = `mutation($id: ID!) {
              convertPullRequestToDraft(input: {pullRequestId: $id}) {
                pullRequest { isDraft }
              }
            }`;
            try {
              await github.graphql(mutation, {
                id: context.payload.pull_request.node_id
              });
              core.notice('PR converted to draft due to CI failure');
            } catch (error) {
              core.warning(`Could not convert to draft: ${error.message}`);
            }
